version: '3.8'
services:
  db:
    image: mysql
    restart: on-failure:3
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - todo_db:/var/lib/mysql

volumes:
  todo_db: {}



